apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../namespace.yaml

configMapGenerator:
- name: custom-templates
  files:
  - custom-templates.yaml

# Component configuration files
- name: jhub-ui-options-form
  files:
  - ../config/ui_options_form.html

- name: jhub-profiles
  files:
  - ../config/profiles.py

- name: jhub-culler-config
  files:
  - ../config/culler.py

- name: jhub-auth-config
  files:
  - ../config/auth.py
