apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

configMapGenerator:
- name: custom-templates
  files:
  - custom-templates.yaml

# Component configuration files
- name: jhub-ui-options-form
  files:
  - ui_options_form.html

- name: jhub-profiles
  files:
  - profiles.py

- name: jhub-culler-config
  files:
  - culler.py

- name: jhub-auth-config
  files:
  - auth.py
