apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # wildcard-secret.yaml removed - create manually with:
  # kubectl create secret tls wildcard-cps-cert --cert=fullchain.pem --key=privkey.pem -n cert-manager
  - clusterissuer.yaml

namespace: cert-manager
