apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# MetalLB CRDs v0.14.9
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_bfdprofiles.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_bgpadvertisements.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_bgppeers.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_communities.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_ipaddresspools.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/crd/bases/metallb.io_l2advertisements.yaml
