apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Disable hash suffix for ConfigMaps so they have predictable names
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: jupyterhub-test-custom-templates
  files:
  - custom-templates.yaml

# Component configuration files
- name: jupyterhub-test-jhub-ui-options-form
  files:
  - ui_options_form.html

- name: jupyterhub-test-jhub-profiles
  files:
  - profiles.py

- name: jupyterhub-test-jhub-culler-config
  files:
  - culler.py

- name: jupyterhub-test-jhub-auth-config
  files:
  - auth.py
